### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/GregTechCompanion-1.5.2#1]
What does this mod do?

**Comment by CrossVas** [comment]
This mod is about `Heating Coils`. In GT3 these are crafter manually using `Crafting Table` directly from ingots. As shown bellow:
![image](https://github.com/CrossVas/GregTechCompanion-1.5.2/assets/25727222/2e269667-6153-4d9a-90c7-cc8febdf60f5)

What this mod does, it addd 3 missing alloy ingots from GT4 which are used to craft these coils in `Wiremill`
![image](https://github.com/CrossVas/GregTechCompanion-1.5.2/assets/25727222/62b60722-e69c-44f6-86c6-159b4d7eb7e5)
